
##########################################
#          Change these variables
##########################################
title:    "Your Site Title"
owner:    "Name Surname"

# Set your 'disqus' account name
disqus: "..."

# Set your host if deployed not locally
url: "https://localhost:4000"


# Set maximum posts per page
paginate: 3



##########################################
#          Do not change these variables
##########################################

include:  ["_pages"]
sass:
  sass_dir: _sass

permalink: "/posts/:year/:month/:title"

gems: [jekyll-paginate]
paginate_path: "/_pages/page:num"
